export { LoginPage } from './login/page'
export { DashboardPage } from './dashboard/page'
export { PatientPage } from './patient/page'
export { SettingsPage } from './settings/page'
export { CompleteProfilePage } from './complete-profile/page'
