export { LoginPage } from './login/page'
export { DashboardPage } from './dashboard/page'
export { TreatmentPage } from './treatment/page'
export { ProfilePage } from './profile/page'
export { CompleteProfilePage } from './complete-profile/page'
